;Calculating all of these values manually is a real pain, not to mention that this process will need to be repeated.
;So I cooked up a quick helper program in C that handles all of this stuff automatically. The source is all in AssistUI.c,
;It's poorly commented but oh so useful for autogenerating the offsets/dimensions/coordinates in the specifications format
;that the UI code expects. So uhhh... what is all this shit anyways? Good quesion. If you take a look in MenubarData.asm
;you'll see the answer. The autogenerated table below is the same type of data. The thing is that when our menubar options are highlighted
;and the user knows which menu option they've selected, these are the magic values that make that happen.

;The currently selected menu option is kept track of in a global variable called "MenuBarOptionSelection". The number that variable
;represents is multiplied by #0Ch and added to the starting address of this table, which will point to the correct label's table 
;information. 

LabelHighlightLUT:

;The first 3 value are null for the purpose of getting the offsets right.
;if the MenuBarOptionSelection variable is 0h, then we skip highlighting.
;the AssistUI C program doesn't take these null values into consideration,
;they were added in manually after auto generating the table.
	DC.L	0x0
	DC.L	0x0
	DC.L	0x0

;File Menu
FileMenuLabels:
	DC.L	0x102
	DC.L	0xa0001
	DC.L	0x10002
	DC.L	0x182
	DC.L	0xa0001
	DC.L	0x10003
	DC.L	0x202
	DC.L	0xa0001
	DC.L	0x10004
	DC.L	0x282
	DC.L	0xa0001
	DC.L	0x10005
	DC.L	0x302
	DC.L	0xa0001
	DC.L	0x10006
	DC.L	0x382
	DC.L	0xa0001
	DC.L	0x10007
;Edit Menu
EditMenuLabels:
	DC.L	0x10
	DC.L	0x90001
	DC.L	0x60002
	DC.L	0x18
	DC.L	0x90001
	DC.L	0x60003
	DC.L	0x20
	DC.L	0x90001
	DC.L	0x60004
	DC.L	0x28
	DC.L	0x90001
	DC.L	0x60005
	DC.L	0x30
	DC.L	0x90001
	DC.L	0x60006
	DC.L	0x38
	DC.L	0x90001
	DC.L	0x60007
	DC.L	0x40
	DC.L	0x90001
	DC.L	0x60008
;View Menu
ViewMenuLabels:
	DC.L	0x116
	DC.L	0x110001
	DC.L	0xb0002
	DC.L	0x196
	DC.L	0x110001
	DC.L	0xb0003
	DC.L	0x216
	DC.L	0x110001
	DC.L	0xb0004
	DC.L	0x296
	DC.L	0x110001
	DC.L	0xb0005
	DC.L	0x316
	DC.L	0x110001
	DC.L	0xb0006
;Help Menu
HelpMenuLabels:
	DC.L	0x102
	DC.L	0x90001
	DC.L	0x10002
	DC.L	0x182
	DC.L	0x90001
	DC.L	0x10003
	DC.L	0x202
	DC.L	0x90001
	DC.L	0x10004
	DC.L	0x282
	DC.L	0x90001
	DC.L	0x10005
;Pattern Sub Menu
PatternSubMenuLabels:
	DC.L	0x11e
	DC.L	0xd0001
	DC.L	0xf0002
	DC.L	0x19e
	DC.L	0xd0001
	DC.L	0xf0003
	DC.L	0x21e
	DC.L	0xd0001
	DC.L	0xf0004
	DC.L	0x29e
	DC.L	0xd0001
	DC.L	0xf0005
	DC.L	0x31e
	DC.L	0xd0001
	DC.L	0xf0006
;Select Sub Menu
SelectSubMenuLabels:
	DC.L	0x19e
	DC.L	0x50001
	DC.L	0xf0003
	DC.L	0x21e
	DC.L	0x50001
	DC.L	0xf0004
;Instruments Sub Menu
InstrumentSubMenuLabels:
	DC.L	0x238
	DC.L	0x70001
	DC.L	0x1c0004
	DC.L	0x2b8
	DC.L	0x70001
	DC.L	0x1c0005
	DC.L	0x338
	DC.L	0x70001
	DC.L	0x1c0006
	DC.L	0x3b8
	DC.L	0x70001
	DC.L	0x1c0007
	DC.L	0x438
	DC.L	0x70001
	DC.L	0x1c0008
